local home = os.getenv('HOME')
local db = require('dashboard')
db.custom_header = {
[[     s                                 ]],
[[    :8                             ..  ]],
[[   .88                            888> ]],
[[  :888ooo      .u         .u      "8P  ]],
[[-*8888888   ud8888.    ud8888.     .   ]],
[[  8888    :888'8888. :888'8888.  u888u.]],
[[  8888    d888 '88%" d888 '88%" `'888E ]],
[[  8888    8888.+"    8888.+"      888E ]],
[[ .8888Lu= 8888L      8888L        888E ]],
[[ ^%888*   '8888c. .+ '8888c. .+   888E ]],
[[   'Y"     "88888%    "88888%     888E ]],
[[             "YP'       "YP'      888E ]],
[[                                  888E ]],
[[                                  888P ]],
[[                                .J88"  ]],
}

 db.custom_center = {
      {icon = '   ',
      desc = 'Recently latest session                 ',
      shortcut = 'SPC s l',
      action ='SessionLoad'},
      {icon = '  ',
      desc = 'Recently opened files                   ',
      action = 'DashboardFindHistory',
      shortcut = 'SPC f h'},
      {icon = '  ',
      desc = 'Find  File                              ',
      action = 'Telescope find_files find_command=rg,--hidden,--files',
      shortcut = 'SPC f f'},
      {icon = '  ',
      desc ='File Browser                            ',
      action =  'Telescope file_browser',
      shortcut = 'SPC f b'},
      {icon = '  ',
      desc = 'Find  word                              ',
      action = 'Telescope live_grep',
      shortcut = 'SPC f w'},
      {icon = '  ',
      desc = 'Open .config files                      ',
      action = 'Telescope find_files path="/Users/tj/.config",--hidden,--files',
      shortcut = 'SPC f d'},
}
